### ISSUE TITLE
Error: Cannot find module 'polyfill-promise'

### ISSUE THREAD

**Issue by LinusU** [jden/node-promise-delay#1]
`polyfill-promise` is required at the top of index.js, but it isn't included in the `dependencies`.

Also, I would really not like it to be included, can't it be up to the user to polyfill if they want to? The problem is that if you include it, `bluebird` will be installed even though native promises will be used.

Even node 0.12 has support for Promises, so I don't think that it's necessary to polyfill...

**Comment by junosuarez** [comment]
Added polyfill-promise to optionalDependencies.
Published as promise-delay@1.0.1
